![piggy_bank](piggy_bank.jpg)

<br>

Personal loans are a lucrative revenue stream for banks. The typical interest rate of a two year loan in the United Kingdom is [around 10%](https://www.experian.com/blogs/ask-experian/whats-a-good-interest-rate-for-a-personal-loan/). This might not sound like a lot, but in September 2022 alone UK consumers borrowed [around £1.5 billion](https://www.ukfinance.org.uk/system/files/2022-12/Household%20Finance%20Review%202022%20Q3-%20Final.pdf), which would mean approximately £300 million in interest generated by banks over two years!

You have been asked to work with a bank to clean and store the data they collected as part of a recent marketing campaign, which aimed to get customers to take out a personal loan. They plan to conduct more marketing campaigns going forward so would like you to set up a PostgreSQL database to store this campaign's data, designing the schema in a way that would allow data from future campaigns to be easily imported. 

They have supplied you with a csv file called `"bank_marketing.csv"`, which you will need to clean, reformat, and split, in order to save separate files based on the tables you will create. It is recommended to use `pandas` for these tasks.

Lastly, you will write the SQL code that the bank can execute to create the tables and populate with the data from the csv files. As the bank are quite strict about their security, you'll save SQL files as multiline string variables that they can then use to create the database on their end. 

You have been asked to design a database that will have three tables:

## client

| column | data type | description | original column in dataset |
|--------|-----------|-------------|----------------------------|
| `id` | `serial` | Client ID - primary key | `client_id` |
| `age` | `integer` | Client's age in years | `age` |
| `job` | `text` | Client's type of job | `job` |
| `marital` | `text` | Client's marital status | `marital` | 
| `education` | `text` | Client's level of education | `education` |
| `credit_default` | `boolean` | Whether the client's credit is in default | `credit_default` |
| `housing` | `boolean` | Whether the client has an existing housing loan (mortgage) | `housing` | 
| `loan` | `boolean` | Whether the client has an existing personal loan | `loan` |

<br>

## campaign

| column | data type | description | original column in dataset |
|--------|-----------|-------------|----------------------------|
| `campaign_id` | `serial` | Campaign ID - primary key | N/A - new column |
| `client_id` | `serial` | Client ID - references `id` in the `client` table | `client_id` |
| `number_contacts` | `integer` | Number of contact attempts to the client in the current campaign | `campaign` |
| `contact_duration` | `integer` | Last contact duration in seconds | `duration` |
| `pdays` | `integer` | Number of days since contact in previous campaign (`999` = not previously contacted) | `pdays` |
| `previous_campaign_contacts` | `integer` | Number of contact attempts to the client in the previous campaign | `previous` |
| `previous_outcome` | `boolean` | Outcome of the previous campaign | `poutcome` |
| `campaign_outcome` | `boolean` | Outcome of the current campaign | `y` |
| `last_contact_date` | `date` | Last date the client was contacted | A combination of `day`, `month`, and the newly created `year` |

<br>

## economics

| column | data type | description | original column in dataset |
|--------|-----------|-------------|----------------------------|
| `client_id` | `serial` | Client ID - references `id` in the `client` table | `client_id` |
| `emp_var_rate` | `float` | Employment variation rate (quarterly indicator) | `emp_var_rate` |
| `cons_price_idx` | `float` | Consumer price index (monthly indicator) | `cons_price_idx` |
| `euribor_three_months` | `float` | Euro Interbank Offered Rate (euribor) three month rate (daily indicator) | `euribor3m` |
| `number_employed` | `float` | Number of employees (quarterly indicator)| `nr_employed` |

##### Read in bank_marketing.csv as a pandas DataFrame.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('bank_marketing.csv')

##### Split the data into three DataFrames using information provided about the desired tables as your guide: one with information about the client, another containing campaign data, and a third to store information about economics at the time of the campaign.

In [ ]:
# Split the df based on the respective columns
client = df.iloc[:, :8]
Campaign = df.loc[:, ['client_id', 'campaign', 'duration', 'pdays', 'previous', 'poutcome', 'y', 'day', 'month']]
economies = df.loc[:, ['client_id', 'emp_var_rate', 'cons_price_idx', 'euribor3m', 'nr_employed']]

##### Rename the column "client_id" to "id" in client (leave as-is in the other subsets); "duration" to "contact_duration", "previous" to "previous_campaign_contacts", "y" to "campaign_outcome", "poutcome" to "previous_outcome", and "campaign" to "number_contacts" in campaign; and "euribor3m" to "euribor_three_months" and "nr_employed" to "number_employed" in economics.

In [2]:
#function to rename columns
def renaming (df, oldname, newname):
    df= df.rename(columns={oldname:newname})
    return df

In [3]:
#applying on the clients table
client= renaming(client,'client_id','id')

In [4]:
#applying the function on the campaign df
Campaign = renaming(Campaign,'duration','contact_duration')
Campaign = renaming(Campaign,'previous','previous_campaign_contacts')
Campaign = renaming(Campaign,'campaign','number_contacts')
Campaign = renaming(Campaign,'y','campaign_outcome')
Campaign = renaming(Campaign,'poutcome','previous_outcome')

In [5]:
#applying the function on the economies df
economies = renaming(economies,'euribor3m','euribor_three_months')
economies = renaming(economies,'nr_employed','number_employed')

##### Clean the "education" column, changing "." to "_" and "unknown" to NumPy's null values.

In [6]:
#fn to handle renaming
def replacement(df,column_name,oldvalue,newvalue):
    #try a str.replace method incase a type error is thrown, a replace method should take over
    try:
        df[column_name]=df[column_name].str.replace(oldvalue,newvalue,regex= False)
        return df
    except TypeError:
        df[column_name]=df[column_name].replace(oldvalue,newvalue)
        return df

In [7]:
#applying the fn
client= replacement(client,'education','.','_') 
client= replacement(client,'education','.',np.nan)

##### Remove periods from the "job" column.

In [8]:
#i use the replacement function above
client= replacement(client,'job','.','')

##### Convert "success" and "failure" in the "previous_outcome" and "campaign_outcome" columns to binary (1 or 0), along with the changing "nonexistent" to NumPy's null values in "previous_outcome".

In [9]:
#function to carry out the conversions
def converter (df,colname,oldvalue,newvalue):
    df.loc[df[colname]==oldvalue,colname] = newvalue
    return df

In [10]:
Campaign = converter(Campaign,'previous_outcome','nonexistent',np.nan)
Campaign = converter(Campaign,'previous_outcome','success',1)
Campaign = converter(Campaign,'previous_outcome','failure',0)
Campaign = converter(Campaign,'campaign_outcome','yes',1)
Campaign = converter(Campaign,'campaign_outcome','no',0)

##### Add a column called campaign_id in campaign, where all rows have a value of 1

In [11]:
Campaign['campaign_id']=1

##### Create a datetime column called last_contact_date, in the format of "year-month-day", where the year is 2022, and the month and day values are taken from the "month" and "day" columns.

In [12]:
#first covert day&month columns to str using astype. then apply a lanbda fn which concats 2022-month-day
Campaign['last_contact_date'] = Campaign[['day','month']].astype(str).apply(lambda x: '2022'+'-'+x['month']+'-'+x['day'], axis=1)
#convert to a datetime type
Campaign['last_contact_date'] = pd.to_datetime(Campaign['last_contact_date'])

##### Remove any redundant data that might have been used to create new columns, ensuring the columns in each subset of the data match the table displayed in the notebook.

In [13]:
Campaign = Campaign.drop(['day', 'month'], axis =1)

##### Save the three DataFrames to csv files without an index as client.csv, campaign.csv, and economics.csv respectively.

In [15]:
Campaign.to_csv('campaign.csv',index=False)
economies.to_csv('economics.csv',index=False)
client.to_csv('client.csv',index=False)

##### Create a Python variable called client_table, containing SQL code as a multi-line string to create a table called client using values from client.csv.

In [20]:
client_table = """CREATE TABLE client
(
    id SERIAL PRIMARY KEY,
    age INTEGER,
    job TEXT,
    marital TEXT,
    education TEXT,
    credit_default BOOLEAN,
    housing BOOLEAN,
    loan BOOLEAN
);
\copy client from 'client.csv' DELIMITER ',' CSV HEADER
"""

##### Create a Python variable called campaign_table, containing SQL code as a multi-line string to create a table called campaign using values from campaign.csv.

In [21]:
campaign_table= """CREATE TABLE campaign
(
    campaign_id SERIAL PRIMARY KEY
    client_id SERIAL references client(id),
    number_contacts INTEGER,
    contact_duration INTEGER,
    pdays INTEGER,
    previous_campaign_contacts INTEGER,
    previous_outcome BOOLEAN,
    campaign_outcome BOOLEAN,
    last_contact_date DATE
)
\copy campaign from 'campaign.csv' DELIMITER ',' CSV HEADER
"""

##### Create a Python variable called economics_table, containing SQL code as a multi-line string to create a table called economics using values from economics.csv.

In [22]:
economies_table = """CREATE TABLE economies
(
    client_id SERIAL references client(id),
    emp_var_rate FLOAT,
    cons_price_idx FLOAT,
    euribor_three_months FLOAT,
    number_employed FLOAT
)
\copy economics from 'economics.csv' DELIMITER ',' CSV HEADER
"""